name: boed-elife
channels:
    - pytorch
    - conda-forge
dependencies:
    - python=3.8
    - pytorch
    - matplotlib
    - tqdm
    - scipy
    - numpy
    - notebook
    - nodejs
    - requests
    - joblib 
    - pytest
    - ax-platform=0.1.20
